name: scala-utils linting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup luacheck
      run: |
        sudo apt update &&
        sudo apt install -y lua5.1 luarocks &&
        sudo luarocks install luacheck
    - name: Run luacheck
      run: make lint
  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup StyLua
      run: cargo install --version 0.8.1 stylua
    - name: run StyLua
      run: make format-check
