name: scala-utils linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup luacheck
      run: |
        sudo apt update &&
        sudo apt install -y lua5.1 luarocks &&
        sudo luarocks install luacheck
    - name: Run luacheck
      run: make lint

  format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run StyLua
      uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.11.0
        args: --check lua/
